name: "Cloudflare Deploy"
description: "Deploy to Cloudflare Pages"

inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  repository:
    description: 'The GitHub repository to deploy, in the format "organization/repository"'
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true
  extra_secrets:
    description: "A serialized JSON object containing any extra secrets necessary for the specific deployment"
    required: false

runs:
  using: "composite"
  steps:
    - name: Extract repository name
      id: repo_name
      run: echo "::set-output name=repo::$(echo ${{ inputs.repository }} | cut -d '/' -f 2)"
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: ${{ steps.repo_name.outputs.repo }}

    - name: Checkout cloudflare-deploy-action
      uses: actions/checkout@v4
      with:
        repository: "ubiquity/cloudflare-deploy-action"
        path: "cloudflare-deploy-action"
    - run: ./cloudflare-deploy-action/cloudflare-deploy.sh ${{ inputs.repository }} ${{ inputs.production_branch }} ${{ inputs.output_directory }} ${{ inputs.extra_secrets }}
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
