name: "Cloudflare Deploy"
description: "Deploy to Cloudflare Pages"
inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  supabase_url:
    description: "Supabase URL"
    required: true
  supabase_key:
    description: "Supabase Key"
    required: true
  repository:
    description: "GitHub Repository"
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true
runs:
  using: "composite"
  steps:
  - run: ls -la
    shell: bash

  - run: ./cloudflare-deploy.sh ${{ inputs.repository }} ${{ inputs.production_branch }} ${{ inputs.output_directory }}
    shell: bash
    env:
      SUPABASE_URL: ${{ inputs.supabase_url }}
      SUPABASE_KEY: ${{ inputs.supabase_key }}
      CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
