name: "Cloudflare Deploy"
description: "Deploy to Cloudflare Pages"
inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  supabase_url:
    description: "Supabase URL"
    required: true
  supabase_key:
    description: "Supabase Key"
    required: true
  repository:
    description: "GitHub Repository"
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout cloudflare-deploy-action
      uses: actions/checkout@v2
      with:
        repository: "ubiquity/cloudflare-deploy-action"
        path: "cloudflare-deploy-action"
    - name: List files in cloudflare-deploy-action
      run: ls -la cloudflare-deploy-action
      shell: bash
    - run: ./cloudflare-deploy-action/cloudflare-deploy.sh ${{ inputs.repository }} ${{ inputs.production_branch }} ${{ inputs.output_directory }}
      shell: bash
      env:
        SUPABASE_URL: ${{ inputs.supabase_url }}
        SUPABASE_KEY: ${{ inputs.supabase_key }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
