name: "Continuous Deployment to Cloudflare Pages"
description: "Deploy to Cloudflare Pages"

inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  repository:
    description: 'The GitHub repository to deploy, in the format "organization/repository"'
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true
  current_branch:
    description: "Compare if not production branch for preview deploys"
    required: true
  pull_request_number:
    description: "Pull request number for posting the deployment link"
    required: false
  commit_sha:
    description: "Commit SHA for posting the deployment link"
    required: false
  # app_private_key:
  #   description: "App Private Key"
  #   required: true
  # app_id:
  #   description: "App ID"
  #   required: true
  # app_installation_id:
  #   description: "App Installation ID"
  #   required: true

runs:
  using: "composite"
  steps:
    - name: Check for pull_request_number or commit_sha
      shell: bash
      run: |
        if [ -z "${{ inputs.pull_request_number }}" ] && [ -z "${{ inputs.commit_sha }}" ]; then
          echo "Error: Either pull_request_number or commit_sha must be provided."
          exit 1
        fi

    - name: Deploy to Cloudflare
      run: bash ../../_actions/ubiquity/cloudflare-deploy-action/main/.github/cloudflare-deploy.sh "${{ inputs.repository }}" "${{ inputs.production_branch }}" "${{ inputs.output_directory }}" "${{ inputs.current_branch }}"
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}

    - name: Post Deployment on Pull Request or Commit
      run: |
        cd ../../_actions/ubiquity/cloudflare-deploy-action/main
        yarn add tsx -D
        yarn tsx post-deployment.ts --deployment_output "${{ env.DEPLOYMENT_OUTPUT }}" --repository "${{ inputs.repository }}" --pull_request_number "${{ inputs.pull_request_number }}" --commit_sha "${{ inputs.commit_sha }}"
      shell: bash
