name: "Cloudflare Deploy"
description: "Deploy to Cloudflare Pages"

inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  repository:
    description: 'The GitHub repository to deploy, in the format "organization/repository"'
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true

runs:
  # Docker is more efficient than running manually according to ChatGPT
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.production_branch }}
    - ${{ inputs.output_directory }}
  env:
    CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
