name: "Cloudflare Deploy"
description: "Deploy to Cloudflare Pages"

inputs:
  repository:
    description: 'The GitHub repository to deploy, in the format "organization/repository"'
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true

runs:
  using: "composite"
  steps:
    - run: ./cloudflare-deploy.sh ${{ inputs.repository }} ${{ inputs.production_branch }} ${{ inputs.output_directory }}
      shell: bash
      # env:
      #   CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}