name: "Cloudflare Deploy"
description: "Deploy to Cloudflare Pages"
inputs:
  cloudflare_api_token:
    description: "Cloudflare API Token"
    required: true
  supabase_url:
    description: "Supabase URL"
    required: true
  supabase_key:
    description: "Supabase Key"
    required: true
  repository:
    description: "GitHub Repository"
    required: true
  production_branch:
    description: "Production Branch"
    required: true
  output_directory:
    description: "Output Directory"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        git clone https://github.com/${{ inputs.repository }} .
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        source ~/.bashrc
        nvm install 20.10.0
        nvm use 20.10.0
        node --version
        yarn install
        yarn build
        yarn add wrangler
      shell: bash
      env:
        SUPABASE_URL: ${{ inputs.supabase_url }}
        SUPABASE_KEY: ${{ inputs.supabase_key }}

    - run: |
        IFS='/' read -ra fields <<< "${{ inputs.repository }}"
        projectName="${fields[1]//./-}"
        echo $projectName
        yarn wrangler pages project list > project_list.txt
        if grep -q $projectName project_list.txt; then
          echo "Project found"
        else
          echo "Project not found"
          yarn wrangler pages project create "$projectName" --production-branch "${{ inputs.production_branch }}"
        fi
        yarn wrangler pages deploy "${{ inputs.output_directory }}" --project-name "$projectName"
      shell: bash
      env:
        CLOUDFLARE_API_TOKEN: ${{ inputs.cloudflare_api_token }}
