name: Test Action Locally
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log all inputs
        run: |
          echo "Cloudflare API Token: ${{ secrets.CLOUDFLARE_API_TOKEN }}"
          echo "Repository: ${{ github.repository }}"
          echo "Production Branch: ${{ github.ref }}"
          echo "Output Directory: ${{ github.workspace }}"
          echo "Current Branch: ${{ env.GITHUB_REF_NAME }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run my custom action
        uses: ./ # Points to the project root where action.yml is located
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          repository: ${{ github.repository }}
          production_branch: ${{ github.ref }}
          output_directory: ${{ github.workspace }}
          current_branch: ${{ env.GITHUB_REF_NAME }}
